Add item requests
SemekhinV/java-shareit pull request #8
Opened 2023-09-08 18:15 UTC by SemekhinV

2023-09-09 18:55 UTC, NikolaiDem requested changes

2023-09-09 18:55 UTC, NikolaiDem commented on src/main/java/ru/practicum/shareit/booking/dtotest/BookingRepository.java
> +            Long booker_id, LocalDateTime endDate, Pageable pageable);
Кодстайл: в Java принят camelCase 
booker_id -> bookerId
Аналогично в остальных методах и классах.
Расстояние между методами в одну строку

2023-09-09 18:55 UTC, NikolaiDem commented on src/main/java/ru/practicum/shareit/booking/service/BookingService.java
> +    List<BookingAllFieldsDto> getAllBookingsOfCurrentUser(Long userId, String state, Integer from, Integer size);
Integer from, Integer size лучше заменить на Pageable
Аналогично в остальных сервисах и методах

2023-09-09 18:55 UTC, NikolaiDem commented on src/main/java/ru/practicum/shareit/booking/service/BookingServiceImpl.java
>      private void isValid(BookingFromRequestDto booking) {
Почему используется кастомная валидация вместо использования аннотаций валидаций из javax.constraints ?

2023-09-09 18:55 UTC, NikolaiDem commented on src/main/java/ru/practicum/shareit/booking/service/BookingServiceImpl.java
> +        if (userId == null) {throw new BadInputParametersException("Передан пустой параметр.");}
Кодстайл: скобки должны быть на отдельных строках

2023-09-09 18:55 UTC, NikolaiDem commented on src/main/java/ru/practicum/shareit/booking/service/BookingServiceImpl.java
> +        var page = PageRequestImpl.of(from, size, Sort.by("startDate").descending());
Чтобы избавиться от проверок page на null, лучше задавать дефолтный page, если from и size не заданы. Аналогично для остальных запросов и методов

2023-09-09 18:55 UTC, NikolaiDem commented on src/main/java/ru/practicum/shareit/booking/service/BookingServiceImpl.java
> +        if (Status.ALL.name().equals(state) || state == null) {
Лучше state преобразовать в Status сразу, сделать switch case, и для неизвестного Status бросить исключение

2023-09-09 18:55 UTC, NikolaiDem commented on src/main/java/ru/practicum/shareit/item/service/ItemService.java
> +    @Transactional
Transactional уже указан в реализации сервиса. Тогда в интерфейсе аннотация лишняя

2023-09-09 18:55 UTC, NikolaiDem commented on src/main/java/ru/practicum/shareit/item/service/ItemServiceImpl.java
> +        var page = PageRequestImpl.of(from, size, Sort.by("id").ascending());
Сделать page таким, чтобы он не был null, указав дефолтные значения для from и size.
Аналогично в остальных методах

2023-09-09 18:55 UTC, NikolaiDem commented on src/main/java/ru/practicum/shareit/request/controller/ItemRequestController.java
> +            @RequestHeader(value = "X-Sharer-User-Id", required = false) Long userId,
Вынести X-Sharer-User-Id в константы.
Аналогично для остальных контроллеров

2023-09-09 18:55 UTC, NikolaiDem commented on src/main/java/ru/practicum/shareit/request/repository/ItemRequestRepository.java
> +    List<ItemRequest> findItemRequestsByRequester_IdIsNotOrderByCreatedDesc(Long requester_id, Pageable pageable);
Кодстайл: расстояние между методами должно составлять 1 пустую строку

2023-09-09 18:55 UTC, NikolaiDem commented on src/main/java/ru/practicum/shareit/request/service/ItemRequestServiceImpl.java
> +        if (userId == null) {
Проверки на null параметров запроса лучше перенести в контроллер, добавив перед ними NotNull в эндпоинте. Аналогично для остальных сервисов

2023-09-09 18:55 UTC, NikolaiDem commented on src/main/java/ru/practicum/shareit/tools/PageRequestImpl.java
> +        if (size == null || from == null) return null;
Можно проверить эти параметры с помощью аннотаций в контроллере

2023-09-09 18:55 UTC, NikolaiDem commented on src/main/java/ru/practicum/shareit/booking/dtotest/BookingRepository.java
> +package ru.practicum.shareit.booking.dtotest;
Почему dtotest?

2023-09-09 18:55 UTC, NikolaiDem commented on src/main/java/ru/practicum/shareit/item/mapper/ItemMapper.java
> +                .userId(item.getOwner() != null ? item.getOwner().getId() : null)
А предполагается отсутствие owner-а у item?

2023-09-09 19:41 UTC, SemekhinV commented on src/main/java/ru/practicum/shareit/booking/service/BookingServiceImpl.java
>      private void isValid(BookingFromRequestDto booking) {
Здравствуйте, кастомную валидацию я использую тк при добавлении аннотации в dto или модели начнутся проблемы с мапперами и некоторыми методами, а так же из-за возможности вернуть кастомную ошибку (про возможность изменить сообщение об ошибке в аннотации знаю). Если вы подскажете, как улучшить эту часть кода - запомню и буду очень благодарен, тк в процессе разработки мне показалось данное решение неплохим.

2023-09-09 19:47 UTC, SemekhinV commented on src/main/java/ru/practicum/shareit/request/controller/ItemRequestController.java
> +            @RequestHeader(value = "X-Sharer-User-Id", required = false) Long userId,
Сделал, но не могли бы вы немного подробнее объяснить, в чем преимущество данного решения?

2023-09-09 20:15 UTC, SemekhinV commented on src/main/java/ru/practicum/shareit/item/mapper/ItemMapper.java
> +                .userId(item.getOwner() != null ? item.getOwner().getId() : null)
Исправил

2023-09-09 20:15 UTC, SemekhinV commented on src/main/java/ru/practicum/shareit/booking/dtotest/BookingRepository.java
> +package ru.practicum.shareit.booking.dtotest;
Случайно переименовал, когда писал тесты, исправил

2023-09-09 20:26 UTC, SemekhinV commented on src/main/java/ru/practicum/shareit/tools/PageRequestImpl.java
> +        if (size == null || from == null) return null;
Исправил

2023-09-09 20:26 UTC, SemekhinV commented on src/main/java/ru/practicum/shareit/request/service/ItemRequestServiceImpl.java
> +        if (userId == null) {
Исправил

2023-09-09 20:26 UTC, SemekhinV commented on src/main/java/ru/practicum/shareit/request/repository/ItemRequestRepository.java
> +    List<ItemRequest> findItemRequestsByRequester_IdIsNotOrderByCreatedDesc(Long requester_id, Pageable pageable);
Исправил

2023-09-09 20:28 UTC, SemekhinV commented on src/main/java/ru/practicum/shareit/item/service/ItemService.java
> +    @Transactional
Исправил

2023-09-09 20:29 UTC, SemekhinV commented on src/main/java/ru/practicum/shareit/booking/service/BookingServiceImpl.java
> +        if (userId == null) {throw new BadInputParametersException("Передан пустой параметр.");}
Исправил здесь и в остальном коде

2023-09-09 20:29 UTC, SemekhinV commented on src/main/java/ru/practicum/shareit/booking/dtotest/BookingRepository.java
> +            Long booker_id, LocalDateTime endDate, Pageable pageable);
Исправил

2023-09-10 10:16 UTC, SemekhinV commented on src/main/java/ru/practicum/shareit/booking/service/BookingService.java
> +    List<BookingAllFieldsDto> getAllBookingsOfCurrentUser(Long userId, String state, Integer from, Integer size);
Не могли бы вы объяснить, в чем преимущество данного решения? Отдельный пользовательский класс, на мой скромный взгляд, сильно упрощает код контроллеров и позволяет вынести проверки в одно единственное место, а так же позволяет избежать проблем в случае, когда from и size не заданы, тк невозможно узнать количество элементов, которые вернет метод репозитория. А так же появляется новая проблема - у аннотаций нельзя изменить код ошибки, из-за чего начинается проблема с прохождением postman тестов

2023-09-10 11:12 UTC, SemekhinV commented on src/main/java/ru/practicum/shareit/booking/service/BookingServiceImpl.java
> +        var page = PageRequestImpl.of(from, size, Sort.by("startDate").descending());
Добавил значения по умолчанию

2023-09-10 11:51 UTC, SemekhinV commented on src/main/java/ru/practicum/shareit/booking/service/BookingServiceImpl.java
> +        if (Status.ALL.name().equals(state) || state == null) {
Сделал

2023-09-10 13:17 UTC, SemekhinV commented
Николай, я по глупости поменял версию языка с 11 на 14 и жутко запутался в процессе, поэтому commit 2.1 от 2.1.4 отличается лишь измененным switch и двумя цифрами в pom.

2023-09-11 17:01 UTC, NikolaiDem commented on src/main/java/ru/practicum/shareit/booking/service/BookingServiceImpl.java
> +        if (Status.ALL.name().equals(state) || state == null) {
Лучше привести к виду:

    public List<BookingAllFieldsDto> getAllBookingsOfCurrentUser(Long userId, String state) {
        userService.getUser(userId);

        List<Booking> response;
        Status status = Status.valueOf(state);
        switch (status) {
            case PAST:
                response = bookingRepository.findBookingByBookerIdIsAndEndDateBeforeOrderByStartDateDesc(userId, LocalDateTime.now());
                break;
            case CURRENT:
                response = bookingRepository.findBookingByBookerIdIsAndStartDateBeforeAndEndDateAfterOrderByStartDateDesc(userId, LocalDateTime.now(), LocalDateTime.now());
                break;
                //Здесь добавить остальные статусы
            case ALL:
            default:
                response = bookingRepository.findBookingsByBookerIdIsOrderByStartDateDesc(userId);
        }

        return response
                .stream()
                .map(BookingMapper::toAllFieldsDto)
                .collect(Collectors.toList());
    }

Аналогично для getAllBookingsOfCurrentUser

2023-09-11 17:01 UTC, NikolaiDem commented on src/main/java/ru/practicum/shareit/booking/service/BookingServiceImpl.java
> +
Что-то много пустых строк)

2023-09-11 17:01 UTC, NikolaiDem commented on src/main/java/ru/practicum/shareit/booking/service/BookingServiceImpl.java
> +                    );
Лучше не разбрасывать скобки по разным строкам. Читается легче)
Аналогично для getAllUserItemsBookings

2023-09-11 17:01 UTC, NikolaiDem commented on src/main/java/ru/practicum/shareit/booking/service/BookingServiceImpl.java
> +        } catch (IllegalArgumentException e) {
Перехватывать рантайм исключения - нехорошая практика.
Аналогично для getAllUserItemsBookings

2023-09-11 17:01 UTC, NikolaiDem commented on src/main/java/ru/practicum/shareit/booking/service/BookingServiceImpl.java
>      private void isValid(BookingFromRequestDto booking) {
При добавлении аннотаций в dto какие проблемы начинаются?

2023-09-11 17:09 UTC, NikolaiDem requested changes

2023-09-11 17:09 UTC, NikolaiDem commented on src/main/java/ru/practicum/shareit/item/mapper/ItemMapper.java
> +                .userId(item.getOwner() != null ? item.getOwner().getId() : null)
Таки при сохранении Item id хозяина передается. А в каком случае у item не будет хозяина?

2023-09-11 17:09 UTC, NikolaiDem commented on src/main/java/ru/practicum/shareit/item/service/ItemService.java
> +    @Transactional
Аннотации лучше перенести в реализацию сервиса

2023-09-11 17:09 UTC, NikolaiDem commented on src/main/java/ru/practicum/shareit/request/service/ItemRequestServiceImpl.java
> +        if (userId == null) {
Исправлено не везде

2023-09-12 12:56 UTC, closed without merging